* Control.h
* Defines for window style control features

#define CHOICE 1
#define ACTION 2

#define PREVFIELD       -1
#define NEXTFIELD       1
#define ENDREAD         0
#define SAVEREAD        2      
#define CHANGE          -2
#define CHANGE_NEXT     3
#define HELP            4
#define ADD_NEW         -3

// For status function
#define ST_LEN     4       // Length of status array
#define ST_ROW     1       // Status item display row
#define ST_COL     2       // Status item display column
#define ST_COLOR   3       // Status item color
#define ST_CURRENT 4       // Status item current position in aDisplay


#define BASE_COLOR      "B+/N"
#define BUTTON_ON       "W+/R"
#define BUTTON_OFF      "W/B"
#define CONTROL_COLOR   "W+/B"
#define WIN_COLOR       "B/W,W+/R"
#define TITLE_ON        "W+/R"
#define TITLE_OFF       "GR+/B"
#define SELECT_COLOR    "GR+/B"
#define BROW_COLOR      "N/W"
#define LOG_ON          "R/W"
#define SHADOW          "N+/N"
#define STAT_COLOR      "W+/R"






